services:
  db:
    image: iesper/home-library-service:db
    build:
      context: .
      dockerfile: Dockerfile.postgres
    container_name: home-library-service-db
    restart: always
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
      - db_logs:/var/log/postgresql
    networks:
      - homelibrary-net

  app:
    image: iesper/home-library-service:app
    build:
      context: .
      dockerfile: Dockerfile
    container_name: home-library-service-app
    restart: always
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - db
    networks:
      - homelibrary-net

volumes:
  db_data:
  db_logs:

networks:
  homelibrary-net:
    driver: bridge