# syntax=docker/dockerfile:1
# FROM postgres:16-alpine
FROM postgres:16

COPY postgresql.conf /docker-entrypoint-initdb.d/
COPY init-config.sh /docker-entrypoint-initdb.d/
RUN chmod +x /docker-entrypoint-initdb.d/init-config.sh