services:
  db:
    image: postgres:16
    container_name: postgres-db
    restart: always
    environment: {}
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
      - db_logs:/var/log/postgresql
    networks:
      - homelibrary-net

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: home-library-service
    restart: always
    env_file:
      - .env
    environment: {}
    # volumes:
    #   - .:/app
    ports:
      - "4000:4000"
    depends_on:
      - db
    networks:
      - homelibrary-net
    develop:
      watch:
        - path: .
          target: /app
          action: sync
          ignore:
            - node_modules/
            - dist/
            - .git/
            - logs/
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - homelibrary-net

volumes:
  db_data:
  db_logs:

networks:
  homelibrary-net:
    driver: bridge
